package com.kommhub.model.db;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A redeemable code that grants a badge. Generated by a SUPER_ADMIN on the web
 * dashboard, redeemed by users from the client. Limited by an optional expiry
 * (claim window) and an optional max redemption count; the badge itself never
 * expires once awarded.
 */
@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "badge_tokens",
        indexes = @Index(name = "idx_badge_token_badge", columnList = "badge_id"))
public class BadgeToken {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "badge_token_id", nullable = false, length = 36)
    private UUID badgeTokenId;

    @Column(name = "token_value", nullable = false, unique = true, length = 32)
    private String tokenValue;

    @Column(name = "badge_id", nullable = false, length = 36)
    private UUID badgeId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "badge_id", insertable = false, updatable = false)
    @JsonIgnore
    private Badge badge;

    // null = unlimited redemptions
    @Column(name = "max_uses")
    private Integer maxUses;

    @Column(name = "used_count", nullable = false)
    @Builder.Default
    private int usedCount = 0;

    // null = never expires
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    public boolean isExpired() {
        return expiresAt != null && LocalDateTime.now().isAfter(expiresAt);
    }

    public boolean isExhausted() {
        return maxUses != null && usedCount >= maxUses;
    }
}
